### ISSUE TITLE
模板变量不对应

### ISSUE THREAD

**Issue by jfgg95** [wang1xiang/wechat_message#1]
建议把模板修改成

> {{nowDate.DATA}} 城市：{{city.DATA}}
> 
> 天气： {{weather.DATA}}
> 
> 气温： {{temperature.DATA}}
> 
> 今天是我们恋爱的 {{loveDate.DATA}} 天
> 
> 
> {{txt.DATA}}

**Comment by wang1xiang** [comment]
> 建议把模板修改成
> 
> > {{nowDate.DATA}} 城市：{{city.DATA}}
> > 天气： {{weather.DATA}}
> > 气温： {{temperature.DATA}}
> > 今天是我们恋爱的 {{loveDate.DATA}} 天
> > {{txt.DATA}}

嗯嗯 忘记贴模板了 确实是你写的这样 已加在README里
